#ifndef API_TIMER_HPP
#define API_TIMER_HPP

enum COMMAND_TIMER_ID
{
    COMMAND_GET_CURRENT_TIME
    , COMMAND_START_COUNT_TIME
    , COMMAND_PAUSE_COUNT_TIME
    , COMMAND_CONTINUE_COUNT_TIME
};

enum RESPONSE_TIMER_ID
{
    RESPONSE_GET_CURRENT_TIME
    , RESPONSE_START_COUNT_TIME
    , RESPONSE_PAUSE_COUNT_TIME
    , RESPONSE_CONTINUE_COUNT_TIME
};

#endif //API_TIMER_HPP
