#ifndef API_STATEMACHINE_HPP
#define API_STATEMACHINE_HPP

enum COLOUR_STATE
{
    DEFAULT
    , RED
    , YELLOW_TO_RED
    , YELLOW_TO_GREEN
    , GREEN
};

enum WORK_STATE
{
    NOT_STARTED
    , WORKING
    , PAUSED
};

enum COMMAND_STATEMACHINE_ID
{
    COMMAND_START_STATEMACHINE
    , COMMAND_PAUSE_STATEMACHINE
    , COMMAND_CHANGE_COLOUR_STATE
    , COMMAND_GET_CURRENT_COLOUR_STATE
};

enum RESPONSE_STATEMACHINE_ID
{
    RESPONSE_START_STATEMACHINE
    , RESPONSE_PAUSE_STATEMACHINE
    , RESPONSE_CHANGE_COLOUR_STATE
    , RESPONSE_GET_CURRENT_COLOUR_STATE
};

#endif //API_STATEMACHINE_HPP
