#ifndef API_MANAGER_HPP
#define API_MANAGER_HPP

enum COMMAND_MANAGER_ID
{
    COMMAND_COUNT_TIME_IS_FINISHED
    , COMMAND_USER_PRESS_START
    , COMMAND_USER_PRESS_PAUSE
    , COMMAND_USER_PRESS_EXIT    
};

enum RESPONSE_MANAGER_ID
{
    RESPONSE_COUNT_TIME_IS_FINISHED
    , RESPONSE_USER_PRESS_START
    , RESPONSE_USER_PRESS_PAUSE
    , RESPONSE_USER_PRESS_EXIT    
};

#endif //API_MANAGER_HPP
